name: Storytravelers
favicon: null
layout_spectrum: 0.15456594992429018
typography_spectrum: 0.299123810371384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8270872349385172
  lightness: 0.17267797514796257
  saturation: 0.4013222462963313
  rhythmicContrast: 0.39429910853505135
purpose: []
