name: Storytravelers
favicon: null
layout_spectrum: 0
typography_spectrum: 0.11214
title: Storytravelers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c100f'
    - '#b6a592'
    - '#304129'
    - '#fbf4eb'
    - '#677949'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
