typography_spectrum: 0.48776
color:
  brandColors:
    - '#0c100f'
    - '#b6a592'
    - '#304129'
    - '#fbf4eb'
    - '#677949'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43239
analytics:
  google: null
  facebook: null
  twitter: null
name: Storytravelers
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Storytravelers
description: Make your stories travel
purpose: []
